// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Core.Data;

#nullable disable

namespace Shared.Core.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260106120000_AddCustomerMembershipAndEnhancedIndexes")]
    partial class AddCustomerMembershipAndEnhancedIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
            // Model configuration would be generated here by EF Core
            // This is a simplified version for the migration
#pragma warning restore 612, 618
        }
    }
}